### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [TerrenceBeckham/quote_boss#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by TerrenceBeckham** [comment]
Hello Billy
I added this meta tag "meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" to the head of my site as per the instructions here: [bootstrap](https://www.google.com)
Is this what you meant? To be honest, I did not notice a difference on my mobile.

**Comment by BillyMassey** [comment]
The ideal mobile meta tag that’s generally used is this one here:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

If you remove the tag entirely, deploy to heroku, see the before, then add the tag that I suggested and redeploy and see the after if you’re using a smart phone it will be represented differently.

**Comment by BillyMassey** [comment]
****<meta name="viewport" content="width=device-width, initial-scale=1">      ****

**Comment by BillyMassey** [comment]
"<meta name="viewport" content="width=device-width, initial-scale=1">"

**Comment by TerrenceBeckham** [comment]
Hello Bill thanks, I just finished it. It seems that I was deceived by looking at my site in Safari using the slider to make the screen smaller. Was this part of the course instructions and I missed it??

**Comment by BillyMassey** [comment]
Good Job! 👍 

And nope, just something useful I like to point out to students. I think of it as part of the course, in the sense that I'll tell most students about it here, which also gives you a little exposure to resolving Github issues.

**Comment by TerrenceBeckham** [comment]
Thanks a million
